### ISSUE TITLE
iOS target?

### ISSUE THREAD

**Issue by pyrtsa** [robrix/Either#19]
I tried to use Either in a combined Mac/iOS library I'm developing, but looks like this project is only configured for Mac targets. Any reason not to add iOS as well?

**Comment by robrix** [comment]
Only reason right now is that it hasn’t been done yet. @swizzlr has a spike of it in #14, but I dunno the status of that—I assume he’s pretty busy!

**Comment by swizzlr** [comment]
Sorry yes hi please feel free to supercede, I'm not using Either right now but it should be trivialish to add the iOS tests.

**Comment by robrix** [comment]
:+1: thanks @swizzlr.

@pyrtsa: you can feel free to jump in with a PR if you like; if you don’t, I’ll probably get around to it eventually. It could be a while, tho, because I’m not anticipating doing iOS development any time soon.

**Comment by swizzlr** [comment]
I have a suspicion @gfontenot did something a while ago involving automating this mirroring process but I could be losing my mind

**Comment by gfontenot** [comment]
I'm not doing anything crazy in my frameworks. I just have the tests linked into each platform's test bundle. Same with the source files. I'd be happy to open a PR for this here (I've got some free time right now).

**Comment by robrix** [comment]
@gfontenot If it’d be useful to you, :+1: :heart: :bow:, but don’t trouble yourself on my account!

**Comment by pyrtsa** [comment]
Hooray!

**Comment by swizzlr** [comment]
Herooooo

**Comment by robrix** [comment]
:clap: Thank you @gfontenot :bow:
