### ISSUE TITLE
Pinning Cartfile to SHA cause updated dependencies won't be used.

### ISSUE THREAD

**Issue by norio-nomura** [robrix/Either#32]
[Cartfile](https://github.com/robrix/Either/blob/master/Cartfile) pins dependencies to SHA.
After `carthage update` on [Stream](https://github.com/antitypical/Stream/commit/27245ad965c6eec48a7d0cd47a72fd721b23dda5), `Cartfile.resolved` is following:
```
github "robrix/Box" "18d05a56845837eea90a36854c67de2520983bf8"
github "robrix/Prelude" "180e9ae5e60ec47abd8f3e0fa68cafbbbd160abe"
github "robrix/Memo" "1.1.4"
github "robrix/Either" "1.2.1"
```
I'v noticed by fails on building Prelude on building Either on building Stream.
Thanks

**Comment by robrix** [comment]
Good catch. Fixed in #33 and [tagged](https://github.com/robrix/Either/releases/tag/1.2.2).

**Comment by norio-nomura** [comment]
Thanks! :smile:

**Comment by robrix** [comment]
You’re very welcome.
