### ISSUE TITLE
Free functions

### ISSUE THREAD

**Issue by robb** [robrix/Either#34]
Are free versions of `flatMap` and `map` something you'd be interested in merging?

**Comment by robrix** [comment]
Could you describe the motivation for them?

Incidentally, `>>-` is already a free version of `flatMap`; does that suffice for your purposes?

**Comment by robb** [comment]
Free functions play nicer with `|>`, don't they?

Didn't catch `>>-` was a thing :sparkles:

**Comment by robrix** [comment]
@robb I think you might be able to use `Either.map` and `Either.flatMap` with `|>`. Swift methods are curried, so it should be pretty convenient.

**Comment by robb** [comment]
:+1:
