### ISSUE TITLE
Release 1.3.1 is pointing to Prelude's master

### ISSUE THREAD

**Issue by guidomb** [robrix/Either#42]
I think Prelude's version should be fixed instead of using master. This is causing issue when resolving `Cartfile` into `Cartfile.resolved` we other dependencies that use Prelude.

**Comment by robrix** [comment]
Good call :+1:

**Comment by guidomb** [comment]
The weird thing is than this arose since I updated Carthage to version `0.12` and `carthage bootstrap` is failing with 

```
Could not pick a version for github "robrix/Prelude", due to mutually incompatible requirements:
	"a2c66881a5df6ccdb46f16e39523982c05e565c8"
	"master"
```

**Comment by guidomb** [comment]
Well other people is experiencing the same issue

https://github.com/Carthage/Carthage/issues/1080

**Comment by guidomb** [comment]
I was checking the commits in Prelude and seems that you will have to make a release of it first. Any chance of doing so in the near feature? I think this will help a lot of us update to carthage `0.12` which has nice new features.

**Comment by robrix** [comment]
I’ll try to do so tonight.

**Comment by robrix** [comment]
@guidomb: I’ve just added you as a collaborator to Prelude & Either so that you can add new releases for yourself. Sorry for the delay with all of this!

**Comment by guidomb** [comment]
@robrix Thanks! No need to be sorry. I have no problem adding new releases but probably you could help me with the release notes

**Comment by guidomb** [comment]
I've just made the two releases and test it with Carthage `0.12.0` and everything works fine.

**Comment by robrix** [comment]
:bow: Thanks very much @guidomb! Don’t sweat the release notes for now, we can get it in post :grin:
