### ISSUE TITLE
Push update to Cocoapods master repo?

### ISSUE THREAD

**Issue by srubin** [robrix/Either#52]
Would it be possible to keep the Cocoapods podspec up to date, and to push the newest version of Either to the Cocoapods master repo? I realize there's a naming conflict with [this project](https://github.com/runkmc/either).

```
pod 'Either', :git => "https://github.com/robrix/Either", :tag => '2.0.0'
```

is fine. Just thought I'd ask!

**Comment by 335g** [comment]
I think it is good to release the new version of `Either` when Swift 3.1 is released. I will push it to Cocoapods master repo at this moment. 👍

**Comment by alexbredy** [comment]
Hi there, any updates on that? :)

**Comment by 335g** [comment]
I updated `podspec`. I doesn't push the newest version to Cocoapods master repo because of conflict after all ✋
